version: "3.1"

services:
    webserver:
      build: apache
      container_name: saito4-webserver
      volumes: 
        - ./../../:/var/www/html
      ports:
        - "8080:80"

    mailhog:
      image: mailhog/mailhog:latest
      container_name: saito4-mailhog
      ports:
        - "8081:8025"

    mysql:
      image: mysql:5.7
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#      restart: always
      container_name: saito4-mysql
      working_dir: /mysql_data
      volumes:
        - mysql_data:/var/lib/mysql
        - ./db:/docker-entrypoint-initdb.d
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=saito
        - MYSQL_USER=saito
        - MYSQL_PASSWORD=saito
      ports:
        - "8082:3306"

volumes:
    mysql_data:
