version: "3.1"

services:
    webserver:
      build: apache
      container_name: saito6-webserver-74
      volumes:
        - ./../../../:/var/www/html
      ports:
        - "8080:80"
        # Port of Karma test runner
        - "9876:9876"

    mailhog:
      image: mailhog/mailhog:latest
      container_name: saito5-mailhog-7
      ports:
        - "8081:8025"

    mysql:
      image: mysql:5.6
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      # restart: always
      container_name: saito5-mysql-6
      working_dir: /mysql_data
      volumes:
        - mysql_data:/var/lib/mysql
        - ./db:/docker-entrypoint-initdb.d
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=saito
        - MYSQL_USER=saito
        - MYSQL_PASSWORD=saito
      ports:
        - "8082:3306"

volumes:
    mysql_data:
